WebGoat.NET/ViewModels/HomeViewModel.cs
using WebGoatCore.Models;
using System.Collections.Generic;

#pragma warning disable CS8618 // Non-nullable field is uninitialized. Consider declaring as nullable.
namespace WebGoatCore.ViewModels
{
    public class HomeViewModel
    {
        public IEnumerable<Product> TopProducts { get; set; }
    }
}

WebGoat.NET/Controllers/BlogController.cs
using WebGoatCore.Models;
using WebGoatCore.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;

namespace WebGoatCore.Controllers
{
    [Route("[controller]/[action]")]
    public class BlogController : Controller
    {
        private readonly BlogEntryRepository _blogEntryRepository;
        private readonly BlogResponseRepository _blogResponseRepository;

        public BlogController(BlogEntryRepository blogEntryRepository, BlogResponseRepository blogResponseRepository, NorthwindContext context)
        {
            _blogEntryRepository = blogEntryRepository;
            _blogResponseRepository = blogResponseRepository;
        }

        public IActionResult Index()
        {
            return View(_blogEntryRepository.GetTopBlogEntries());
        }

        [HttpGet("{entryId}")]
        public IActionResult Reply(int entryId)
        {
            return View(_blogEntryRepository.GetBlogEntry(entryId));
        }

        [HttpPost("{entryId}")]
        public IActionResult Reply(int entryId, Contents contents)
        {
            var userName = User?.Identity?.Name ?? "Anonymous";
            var response = new BlogResponse()
            {
                Author = userName,
                Contents = contents,
                BlogEntryId = entryId,
                ResponseDate = DateTime.Now
            };
            _blogResponseRepository.CreateBlogResponse(response);

            return RedirectToAction("Index");
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public IActionResult Create() => View();

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public IActionResult Create(string title, Contents contents)
        {
            var blogEntry = _blogEntryRepository.CreateBlogEntry(title, contents, User!.Identity!.Name!);
            return View(blogEntry);
        }

    }
}

WebGoat.NET/Controllers/HomeController.cs
using WebGoatCore.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using WebGoatCore.ViewModels;
using Microsoft.AspNetCore.Diagnostics;

namespace WebGoatCore.Controllers
{
    [AllowAnonymous]
    public class HomeController : Controller
    {
        private readonly ProductRepository _productRepository;

        public HomeController(ProductRepository productRepository)
        {
            _productRepository = productRepository;
        }

        public IActionResult Index()
        {
            return View(new HomeViewModel()
            {
                TopProducts = _productRepository.GetTopProducts(4)
            });
        }

        public IActionResult About() => View();

        [Authorize(Roles = "Admin")]
        public IActionResult Admin() => View();

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel
            {
                RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier,
                ExceptionInfo = HttpContext.Features.Get<IExceptionHandlerPathFeature>(),
            });
        }
    }
}

WebGoat.NET/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}

<div class="owaspTopTen">
    <h2>
        About WebGoat.NetCore
    </h2>
    <div>
        Welcome to WebGoat.NetCore, an intentionally insecure ecommerce website created so that
        you and I can learn to create intentionally secure websites. We've introduced vulnerabilities
        covering the OWASP Top Ten as well as several others.
    </div>
    <div>
        TODO
    </div>
</div>

WebGoat.NET/Views/Home/Admin.cshtml
@{
    ViewData["Title"] = "Admin";
}

<h1>Administrator Functions</h1>
<a asp-controller="Order" asp-action="Manage">Manage orders</a>
<br>
<a asp-controller="Product" asp-action="Manage">Manage products</a>
<br>
<a asp-controller="Blog" asp-action="Create">Write a blog entry</a>
<br>

WebGoat.NET/Views/Home/Index.cshtml
@model HomeViewModel

@{
    ViewData["Title"] = "Home Page";
}

<h2>
    Welcome to the WebGoat.NetCore Store
</h2>
<p>
    We focus on supplying high-end specialty restaurants with the best quality foods
    sourced from around the world and shipped to your door.
</p>
<h3>
    Today's featured items
</h3>
<br>
<div class="productListItem">
    @foreach (var product in Model.TopProducts)
    {
        <figure>
            <a asp-controller="Product" asp-action="Details" asp-route-productId=@product.ProductId>
                <img src="Images/ProductImages/@(product.ProductId).jpg" alt="@product.ProductName">
            </a>
            <figcaption>@product.ProductName</figcaption>
        </figure>
    }
</div>
<h3>
    Why us?
</h3>
<p>
    Because of our priorities:
</p>
<ul>
    <li>Our food is delicious. Only the finest and the freshest for you. </li>
    <li>
        It's all about your restaurant. We make you look good. We'll only sell the star
        of the plate, the conversation piece of the meal, or that hidden ingredient that
        makes a dish's character.
    </li>
    <li>
        We listen to you. When you call us we'll answer and take the time that we need with
        you.
    </li>
    <li>
        We're real. We don't fake our decisions about what to sell, how to describe the
        food or just about everything else.
    </li>
</ul>